[build-system]
requires = ["setuptools>=42", "wheel", "Cython"]
build-backend = "setuptools.build_meta"
[project]
name = "dual_autodiff_x"
version = "0.0.1b2" # or whatever you want
description = "A package"
[tool.setuptools.packages.find]
where = ["."]
